id: galaxy-milkyway
name: Vía Láctea
planeNormal:
  x: 0
  y: 0
  z: 1
systems:
  system-solar:
    id: system-solar
    name: Sistema Solar
    position:
      x: 0
      y: 0
    localPosition:
      x: 0
      y: 0
      z: 0
    stars:
      - id: star-sun
        name: Sol
        massKg: 1.989e30
        radiusM: 6.9634e8
    planets:
      planet-mercury:
        id: planet-mercury
        name: Mercurio
        class: rocky
        massKg: 3.3011e23
        radiusM: 2.4397e6
        gravity: 3.7
        hasAtmosphere: false
        orbit:
          centerId: star-sun
          semiMajorAxis: 57.9e6
          eccentricity: 0.2056
          inclination: 7.0
          period: 7600530
          phaseAtEpoch: 0
      planet-earth:
        id: planet-earth
        name: Tierra
        class: rocky
        massKg: 5.972e24
        radiusM: 6.371e6
        gravity: 9.8
        hasAtmosphere: true
        orbit:
          centerId: star-sun
          semiMajorAxis: 149.6e6
          eccentricity: 0.0167
          inclination: 0
          period: 31557600
          phaseAtEpoch: 1.5707963267948966
        moons:
          - id: moon-luna
            name: Luna
            class: rocky
            massKg: 7.342e22
            radiusM: 1.737e6
            gravity: 1.62
            hasAtmosphere: false
            orbit:
              centerId: planet-earth
              semiMajorAxis: 384400
              eccentricity: 0.0549
              inclination: 5.145
              period: 2360591
              phaseAtEpoch: 0
  system-proxima:
    id: system-proxima
    name: Proxima Centauri
    position:
      x: 4.24
      y: 0
    localPosition:
      x: 4.24
      y: 0
      z: 0
    stars:
      - id: star-proxima
        name: Proxima Centauri
        massKg: 2.446e29
        radiusM: 9.16e7
    planets:
      planet-proxima-b:
        id: planet-proxima-b
        name: Proxima b
        class: rocky
        massKg: 7.595e24
        radiusM: 7000000
        gravity: 10.8
        hasAtmosphere: false
        orbit:
          centerId: star-proxima
          semiMajorAxis: 7.5e6
          eccentricity: 0
          inclination: 0
          period: 9676800
          phaseAtEpoch: 0.2
