---@meta
-- ═══════════════════════════════════════════════════════════════════════
-- DuckEngine Lua API — Type Definitions Index
--
-- This file exists for backward compatibility. All type definitions
-- have been split into dedicated files under `types/`:
--
--   types/core.d.lua    — ScriptModule, Vec3, ComponentType, PropertyType enums
--   types/entity.d.lua  — LuaEntity class (transform, physics, components, resources)
--   types/scene.d.lua   — SceneAPI (events, entity queries)
--   types/input.d.lua   — InputAPI (keyboard, mouse, pointer lock, KeyName enum)
--   types/physics.d.lua — PhysicsAPI (raycast, RaycastHit)
--   types/time.d.lua    — TimeAPI (dt, now)
--   types/math.d.lua    — MathExt (lerp, clamp, EasingName enum, 16 easing curves)
--   types/builtin_scripts.d.lua — Strong typing for built-in script properties
--
-- The Lua Language Server picks up all .d.lua files in the workspace
-- automatically. No manual imports needed.
-- ═══════════════════════════════════════════════════════════════════════
