---@meta
-- ═══════════════════════════════════════════════════════════════════════
-- DuckEngine Scripting v2 — Type Definitions Index
--
-- This file is the main reference and consolidated index for all v2 types.
-- Individual type definitions are in separate module files:
--   • entity_v2.d.lua
--   • events_v2.d.lua
--   • gizmos_v2.d.lua
--   • input_v2.d.lua
--   • math_v2.d.lua
--   • physics_v2.d.lua
--   • scene_v2.d.lua
--   • script_instance_v2.d.lua
--   • time_v2.d.lua
--   • transform_v2.d.lua
--   • scripts_v2.d.lua
--
-- All classes and APIs are suffixed with V2 to avoid conflicts with core v1.
-- ═══════════════════════════════════════════════════════════════════════

