---@meta
-- ═══════════════════════════════════════════════════════════════════════
-- DuckEngine Lua API v2 — Time
-- Frame timing and time scale control.
-- ═══════════════════════════════════════════════════════════════════════

---Time system providing frame timing information (read-only).
---Access via Engine.Time.getElapsed(), Engine.Time.getDelta(), etc.
---@class TimeV2
---@field getDelta fun(): number Delta time for this frame in seconds.
---@field getElapsed fun(): number Total elapsed time in seconds.
---@field getFrameCount fun(): number Total frame count since startup.
---@field getScale fun(): number Time scale multiplier (1.0 = normal speed).
---@field setScale fun(scale: number): nil Set time scale multiplier.
