version: '3.8'

services:
  duck-asset-service:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - das-data:/data/assets
      - das-db:/app/prisma
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/production.db
      - ASSET_STORAGE_PATH=/data/assets
      - ASSET_ADMIN_USER=admin
      - ASSET_ADMIN_PASS=changeme
      - BASE_URL=http://localhost:3000
    restart: unless-stopped

volumes:
  das-data:
    driver: local
  das-db:
    driver: local
