/**
 * Discriminator tag for all engine components.
 * Each component carries exactly one of these string literals as its `type` field.
 */
export type ComponentType =
  | 'name'
  | 'boxGeometry'
  | 'sphereGeometry'
  | 'planeGeometry'
  | 'cylinderGeometry'
  | 'coneGeometry'
  | 'torusGeometry'
  | 'customGeometry'
  | 'fullMesh'
  | 'standardMaterial'
  | 'basicMaterial'
  | 'phongMaterial'
  | 'lambertMaterial'
  | 'basicShaderMaterial'
  | 'standardShaderMaterial'
  | 'physicalShaderMaterial'
  | 'cameraView'
  | 'textureTiling'
  | 'ambientLight'
  | 'directionalLight'
  | 'pointLight'
  | 'spotLight'
  | 'skybox'
  | 'rigidBody'
  | 'gravity'
  | 'sphereCollider'
  | 'boxCollider'
  | 'capsuleCollider'
  | 'cylinderCollider'
  | 'coneCollider'
  | 'terrainCollider'
  | 'lensFlare'
  | 'postProcess'
  | 'script'
  | 'metadata';
